# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-ApacheExtended
version:      1.13
version_from: VERSION
installdirs:  site
requires:
    Carp:                          0
    File::Spec::Functions:         1.3
    IO::File:                      1.09
    Parse::RecDescent:             1.94
    Scalar::Util:                  1.07
    Test::More:                    0.47
    Text::Balanced:                1.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
